# Generated by Django 4.1.1 on 2023-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.TextField()),
                ("descraption", models.TextField()),
                ("price", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="truck_part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.TextField()),
                ("descraption", models.TextField()),
                ("price", models.TextField()),
            ],
        ),
    ]
